import React from "react";
import PolicyLayout from "../Components/PolicyLayout";

export default function TermsConditions() {
    const year = new Date().getFullYear();
  return (
      <div className="min-h-screen bg-gray-50 text-gray-900">
      {/* Header */}
      <header className="border-b bg-white">
        <div className="mx-auto max-w-5xl px-5 py-6 flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold tracking-tight">Terms &amp; Conditions</h1>
            <p className="mt-1 text-sm text-gray-500">
              Jalwa Trading Pvt Ltd • Website:&nbsp;
              <a
                href="https://jalwatrading.store/"
                target="_blank"
                rel="noreferrer"
                className="text-blue-600 underline"
              >
               jalwatrading.store
              </a>
            </p>
          </div>
          <button
            onClick={() => window.print()}
            className="rounded-lg border px-3 py-2 text-sm hover:bg-gray-100"
          >
            Print
          </button>
        </div>
      </header>

      {/* Main */}
      <main className="mx-auto max-w-5xl px-5 py-8">
        <div className="grid gap-8 lg:grid-cols-[280px_1fr]">
          {/* TOC */}
          <aside className="lg:sticky lg:top-6 h-max">
            <div className="rounded-xl border bg-white p-4">
              <h2 className="text-sm font-semibold text-gray-700">Contents</h2>
              <nav className="mt-3 text-sm space-y-2">
                {[
                  ["#t1", "Electronic Record"],
                  ["#t2", "Rule 3(1) Disclosure"],
                  ["#t3", "Platform Owner"],
                  ["#t4", "Acceptance of Terms"],
                  ["#t5", "Definitions"],
                  ["#t6", "Notice of Acceptance"],
                  ["#t7", "Terms of Use (Clauses)"],
                  ["#t8", "Contract Formation"],
                  ["#t9", "Indemnity"],
                  ["#t10", "Force Majeure"],
                  ["#t11", "Governing Law"],
                  ["#t12", "Jurisdiction"],
                  ["#t13", "Contact & Notices"],
                ].map(([href, label]) => (
                  <a key={href} href={href} className="block hover:text-blue-700">
                    {label}
                  </a>
                ))}
              </nav>
            </div>
          </aside>

          {/* Content */}
          <article className="rounded-xl border bg-white p-6 leading-7 text-gray-800">
            <h2 id="t1" className="text-lg font-semibold underline underline-offset-4">
              Terms &amp; Conditions
            </h2>

            <ol className="mt-4 list-decimal space-y-4 pl-6">
              <li>
                This document is an electronic record in terms of the Information Technology Act, 2000 and
                rules thereunder, as applicable, and the amended provisions pertaining to electronic records
                in various statutes as amended by the Information Technology Act, 2000. This electronic
                record is generated by a computer system and does not require any physical or digital
                signatures.
              </li>

              <li id="t2">
                This document is published in accordance with the provisions of Rule 3(1) of the Information
                Technology (Intermediaries Guidelines) Rules, 2011 that require publishing the rules and
                regulations, privacy policy and Terms of Use for access or usage of the domain name
                <span className="whitespace-pre"> </span>
                <a
                  href="https://jalwatrading.store/"
                  target="_blank"
                  rel="noreferrer"
                  className="text-blue-600 underline"
                >
                  https://jalwatrading.store/
                </a>
                , including the related mobile site and mobile application (collectively, the “Platform”).
              </li>

              <li id="t3">
                The Platform is owned by <strong>Jalwa Trading Pvt Ltd</strong>, a company
                incorporated under the Companies Act, 1956, with its registered office at Village Begampur,
                Landmark: Rajiv Nagar (Sumit Tailor), Begumpur, North West Delhi, Delhi, India – 110086
                (hereinafter referred to as “Platform Owner”, “we”, “us”, or “our”).
              </li>

              <li id="t4">
                Your use of the Platform and services and tools are governed by the following terms and
                conditions (“Terms of Use”) as applicable to the Platform, including the applicable policies
                which are incorporated herein by reference. If you transact on the Platform, you shall be
                subject to the policies applicable to such transaction. By mere use of the Platform, you shall
                be contracting with the Platform Owner and these Terms of Use, including the policies,
                constitute your binding obligations with the Platform Owner. These Terms of Use relate to
                your use of our website, goods (as applicable) or services (as applicable) (collectively,
                “Services”). Any terms proposed by you which add to or conflict with these Terms of Use are
                expressly rejected and shall be of no force or effect. These Terms of Use may be modified at
                any time without assigning any reason. It is your responsibility to periodically review these
                Terms of Use to stay informed of updates.
              </li>

              <li id="t5">
                For the purpose of these Terms of Use, wherever the context so requires “you”, “your” or
                “user” shall mean any natural or legal person who has agreed to become a user/buyer on the
                Platform.
              </li>

              <li id="t6" className="font-semibold">
                ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO
                ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THESE TERMS
                CAREFULLY BEFORE PROCEEDING.
              </li>

              <li id="t7">
                The use of the Platform and/or availing of our Services is subject to the following Terms of Use:
                <ol className="mt-2 list-[lower-alpha] space-y-2 pl-6">
                  <li>
                    To access and use the Services, you agree to provide true, accurate and complete
                    information to us during and after registration, and you shall be responsible for all acts
                    done through the use of your registered account on the Platform.
                  </li>
                  <li>
                    Neither we nor any third parties provide any warranty or guarantee as to the accuracy,
                    timeliness, performance, completeness or suitability of the information and materials
                    offered on this website or through the Services, for any specific purpose. You acknowledge
                    that such information and materials may contain inaccuracies or errors and we expressly
                    exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.
                  </li>
                  <li>
                    Your use of our Services and the Platform is solely and entirely at your own risk and
                    discretion, for which we shall not be liable to you in any manner. You are required to
                    independently assess and ensure that the Services meet your requirements.
                  </li>
                  <li>
                    The contents of the Platform and the Services are proprietary to us and/or licensed to us.
                    You will not have any authority to claim any intellectual property rights, title, or interest
                    in the contents, including (without limitation) the design, layout, look and graphics.
                  </li>
                  <li>
                    You acknowledge that unauthorized use of the Platform and/or the Services may lead to
                    action against you as per these Terms of Use and/or applicable laws.
                  </li>
                  <li>You agree to pay us the charges associated with availing the Services.</li>
                  <li>
                    You agree not to use the Platform and/or Services for any purpose that is unlawful, illegal
                    or forbidden by these Terms, or by Indian or local laws that might apply to you.
                  </li>
                  <li>
                    You agree and acknowledge that the Website and the Services may contain links to third
                    party websites. On accessing these links, you will be governed by the terms of use, privacy
                    policy and such other policies of such third party websites. These links are provided for
                    your convenience to provide further information.
                  </li>
                </ol>
              </li>

              <li id="t8">
                You understand that upon initiating a transaction for availing the Services you are entering into
                a legally binding and enforceable contract with the Platform Owner for the Services.
              </li>

              <li id="t9">
                You shall indemnify and hold harmless the Platform Owner, its affiliates, group companies (as
                applicable) and their respective officers, directors, agents, and employees, from any claim or
                demand, or actions including reasonable attorney’s fees, made by any third party or penalty
                imposed due to or arising out of your breach of these Terms of Use, Privacy Policy and other
                policies, or your violation of any law, rules or regulations or the rights (including infringement
                of intellectual property rights) of a third party.
              </li>

              <li id="t10">
                Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any
                failure to perform an obligation under these Terms if performance is prevented or delayed by a
                force majeure event.
              </li>

              <li id="t11">
                These Terms and any dispute or claim relating to them, or their enforceability, shall be governed
                by and construed in accordance with the laws of India.
              </li>

              <li id="t12">
                All disputes arising out of or in connection with these Terms shall be subject to the exclusive
                jurisdiction of the courts in <strong>New Delhi, Delhi</strong>, India.
              </li>

              <li id="t13">
                All concerns or communications relating to these Terms must be communicated to us using the
                contact information provided on the Website.
              </li>
            </ol>
          </article>
        </div>
      </main>

      {/* Footer */}
    
    </div>
 
  );
}